spring:
  application:
    name: spring-reactor-alumno
  r2dbc:
    url: ${R2DBC_URL}
  config:
    import: optional:file:.env[.properties]
app:
  routes:
    alumno:
      save-path: ${ALUMNO_SAVE_PATH}
      filter-path: ${ALUMNO_FILTER_PATH}

